### ISSUE TITLE
Cannot render multiple 3d traces

### ISSUE THREAD

**Issue by Chris7** [ginkgobioworks/plotly-plot#1]
### Description

3d traces "overlap" eachother and only one can be visible at a time
### Expected outcome

I can view multiple 3d traces
### Actual outcome

I can only view 1
### Live Demo

https://gist.github.com/Chris7/e309d4c7c3f07082886d749652338860

**Comment by myw** [comment]
### Summary

This is actually a bug with plotly.js, as I have discovered after careful testing. There's a workaround, and it's been filed.

### Root cause

plotly.js does not handle 3D plotting well when the data ranges of the traces are significantly different (as is the case in your example), and it behaves differently when you set `element.data` then call `Plotly.redraw()`, instead of just calling `Plotly.addTraces(...)`. The latter exhibits more correct behavior by adding/cleaning up the data traces and giving them unique uids.

### Workaround

When adding multiple 3D plots, rather than using `PlotlyPlot#set`, use `PlotlyPlot#addTraces`, which calls `Plotly.addTraces`:

``` javascript
var plotElement = document.getElementById('the-plot');
plotElement.set('data.0',  {'first trace data' });
plotElement.addTraces({'second trace data'})
```

### Resolution

Commented on plotly/plotly.js#403, which seems to be related to this. If no one responds, I'll try to file a separate issue.

If the issue gets resolved on the plotly side, the element should just work as expected. No code changes.
