### ISSUE TITLE
plotly-plot display incorrect when used inside iron-pages view

### ISSUE THREAD

**Issue by timyhac** [ginkgobioworks/plotly-plot#3]
First of all - great project!

### Description
'plotly-plot' elements don't render properly when embedded inside an iron-pages view.
Chrome/Canary seems to be the only browser that doesn't display correctly.

The demo _does_ work, it is only when the plotly-plot element is inside the iron-pages view page that the display is incorrect.

### Expected outcome

Should be able to interact with the plotly element. [Like this](https://i.imgsafe.org/0d6ca9de3e.jpg)

### Actual outcome

The graph is displayed, but the plotly symbols are displayed below the page. Can't interact with the element. [Like this](https://i.imgsafe.org/0d73a40e54.jpg)

### Live Demo
N/A

### Steps to reproduce

1. Install polymer starter-package 
`polymer init starter-package`
2. Install plotly-plot
`bower install plotly-plot`
3. Insert an example plotly-plot element on my-view1.html
```
    <div class="card">
      <plotly-plot id="the-plot"data='[{"x": [1, 2, 3], "y": [4, 11, 23]}]'>
      </plotly-plot>
      <div class="circle">1</div>
      <h1>View One</h1>
      <p>Ut labores minimum atomorum pro. Laudem tibique ut has.
      <p>Lorem ipsum dolor sit amet, per in nusquam nominavi periculis, sit elit oportere ea.Lorem ipsum dolor sit amet, per in nusquam nominavi periculis, sit elit oportere ea.Cu mei vide viris gloriatur, at populo eripuit sit.</p>
    </div>
```

### Browsers Affected

- [X] Chrome (54.0.2840.99 m)
- [X] Chrome Canary (57.0.2925.0 canary)
- [ ] Firefox
- [ ] Safari 9 (Not Tested)
- [ ] Safari 8 (Not Tested)
- [ ] Safari 7 (Not Tested)
- [ ] Edge (Not Tested)
- [ ] IE 11
- [ ] IE 10 (Not Tested)

**Comment by timyhac** [comment]
Also doesn't work with Opera 41.0.2353.69 (Windows 7 32-bit)

**Comment by myw** [comment]
This is because of the Polymer Shadow Dom: turn off that setting and it
should work right! (This took me a while to figure out. I'll add it to the
README)

--
Misha

**Comment by timyhac** [comment]
Fantastic! Yes this resolves the issue on all the browsers mentioned above.
It also resolves an issue in my real-world app that caused firefox and ie to crash - but I didn't think this was related.

What side effects are there in turning off Polymer Shadow Dom? (Appreciate any docs you could link me to)

**Comment by myw** [comment]
Polymer global DOM settings are described in the [docs](https://www.polymer-project.org/1.0/docs/devguide/settings). 

Polymer comes with (and defaults to using) a shim for the Shadow DOM named "Shady DOM". If you're using Shady DOM, [you have to use the Polymer DOM API when manipulating the DOM from JavaScript](https://www.polymer-project.org/1.0/docs/devguide/local-dom). Also, because Shady DOM is not implemented at the browser level, performance is likely worse.

Polymer 2.0 [re-implements Shady DOM in a way that does not require the wrapper](https://www.polymer-project.org/2.0/docs/about_20), and moves closer to standardized Shadow DOM usage by supporting the Shadow DOM v1 spec.

However, in my experience, despite being promised for a long time, the Shadow DOM API is just _not_ ready for production. It's not well-supported in Chrome, even though it's natively implemented. It's buggy: I've had several instances of it causing strange DOM behavior that's nearly impossible to debug. It's not supported natively in other browsers yet, and when it will be, I suspect there will still be a fair amount of bugs to work out.

**Comment by timyhac** [comment]
Thanks @myw - really appreciate the effort you've put into solving this issue. Will close the issue.
